### ISSUE TITLE
AutoMatch queue

### ISSUE THREAD

**Issue by Cooltimmetje** [Cooltimmetje/Skuddbot#28]
- [x] Auto join/match
  - [x] Reaction to auto join/match
  - [x] Command to auto join/match
  - *Auto joining players will be placed in a queue, then when the match starts, they will be placed in a team at random.*

**TASKS**
- [x] Create join queue.
- [x] Alter start conditions.
- [x] Spread players and then fill teams.
