### ISSUE TITLE
Tracking of favorite teammate

### ISSUE THREAD

**Issue by Cooltimmetje** [Cooltimmetje/Skuddbot#31]
- [x] Stat: `TD_FAV_TEAMMATE`
  - *This stat `will keep track of the teammate the user has most teamed up with. AI users will not be counted.*

**Tasks:**
- [x] Change the stat system so it can hide certain stats from the leaderboard.
- [x] Create the stat.
- [x] Tracking of the stat
- [x] Saving/Loading
- [x] Getting the favourite teammate(s)
